const LOAD_JOKE = 'LOAD_JOKE'
const GET_MOBILE = 'GET_MOBILE'
const FETCH_REQUESTED = 'FETCH_REQUESTED'
const FETCH_SUCCEED = 'FETCH_SUCCEED'
const FETCH_FAIL = 'FETCH_FAIL'

export { LOAD_JOKE, GET_MOBILE, FETCH_FAIL, FETCH_SUCCEED, FETCH_REQUESTED }
